# Generated by Django 6.0.4 on 2026-04-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSyncRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_reference', models.CharField(max_length=20)),
                ('clinic_name', models.CharField(max_length=100)),
                ('sync_status', models.CharField(max_length=20)),
                ('last_updated', models.DateTimeField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
